### ISSUE TITLE
IP資訊無法顯示 (not allowed fetch http over https)

### ISSUE THREAD

**Issue by DF-wu** [DF-wu/HideReplier#2]
IP資訊無法顯示 (not allowed fetch http over https)
![image](https://user-images.githubusercontent.com/28750726/85220403-b55aea00-b3dd-11ea-93ac-9dc15cb42b40.png)

不能在https連線fetch http資料....

@stanley2058 點解？

**Comment by stanley2058** [comment]
把http改成https就可以了，因為在有SSL保護(https)的網站瀏覽器不允許載入未受保護的資源(http)

**Comment by DF-wu** [comment]
thx
